### PR TITLE
example http context refactoring

### PR DESCRIPTION
**Pull request by lamg**
In [FsHttp](https://fsprojects.github.io/FsHttp/Composability.html) is possible to refactor clients, so the computation expressions contain less boilerplate code.

The change suggests how this could be done in this project. It's possible to create a client that has the base URL for Threads.net API, and then pass that client to any function that needs to use it.

Example:
```fsharp
let baseHttp = http { config_useBaseUrl baseUrl }
```

```fsharp
let myFunc baseHttp = 
  baseHttp {
     GET …
  }
```

### CODE REVIEW

**Comment by AngelMunoz** [comment]
These looks good, we can extend them to the other requests as well if you may!

**Comment by lamg** [comment]
@AngelMunoz after running the Sample project I got an error showing this in the command line

```
Value: Avalonia.Controls.TextBlock                                                   
Value: Avalonia.Controls.UserControl                                                 
Unhandled exception. System.Exception: The following errors were found:              
                                                                                     
Error at: `$`                                                                        
Expecting an object but instead got:                                                 
null                                                                                 
                                                                                     
Error at: `$`                                                                        
Expecting an object but instead got:                                                 
null                                                                                 
                                                                                     
Error at: `$`                                                                        
Expecting an object but instead got:                                                 
null                                                                                 
                                                                                     
Error at: `$`                                                                        
Expecting an object but instead got:                                                 
null                                                                                 
   at <StartupCode$Threads-Lib>.$Threads.work@87-1.Invoke(FSharpResult`2 _arg1) in /h
ome/lamg/src/Threads.Lib/Threads.Lib/Threads.fs:line 89  
```

That happened when clicking _profiles_ while waiting for the app to do something. I checked your branch and it has the same behavior.

**Comment by AngelMunoz** [comment]
@lamg I made a few updates due some changes I had myself that hadn't pushed and added the extra header context missing from places like insights. Thank you for lending a hand here!

**Comment by AngelMunoz** [comment]
I also have pushed the `fsdocs` branch in order to add documentation bits and pieces in case you want to take a look at that too! 

All in all I think I'm just missing geo-gated API stuff from the Threads API, but I think this covers pretty much all of the important endpoints

**Pull request merged**
